add new branch for lesson 33 for review
Glassyflute/todolist pull request #1
Opened 2023-02-04 16:37 UTC by Glassyflute

Создана новая ветка на ДЗ 33 для проверки.
Создан кастомный пользователь, админ панель.
Проект подключен к БД postgres через docker-compose.

2023-02-05 07:08 UTC, painassasin requested changes
Если ты используешь poetry, файл requirements.txt не нужен

2023-02-05 07:08 UTC, painassasin commented on README.md
> +####### pip install -r requirements.txt
Весь markdown файл как-то странно сформирован - у тебя весь текст через 6 знаков решетки, зачем?)
Тут можно просто писать текст, а код вставляется так
```
pip freeze > requirements.txt
```
Рекомендую изучить [материал](https://gist.github.com/Jekins/2bf2d0638163f1294637)

2023-02-05 07:39 UTC, Glassyflute commented on README.md
> +####### pip install -r requirements.txt
Скорректировала файл README.md. Надеюсь, с коммуникацией в ветке при исправлении отписалась куда надо) Посмотри, пожалуйста.

2023-02-06 06:16 UTC, Glassyflute commented on README.md
> +####### pip install -r requirements.txt
Обновила файл README.md, удалила requirements.txt

2023-02-06 16:21 UTC, painassasin approved these changes

2023-02-06 17:31 UTC, merged