Dev 36
Glassyflute/todolist pull request #4
Opened 2023-02-26 13:33 UTC by Glassyflute

Высылаю ДЗ 36, на бэкэнде все работает. На фронте комменты на карточке Цели не выводятся, хотя при создании коммента статус 201 на бэкэнде и фронте, плюс отбивка от фронта, что успешно создан коммент. Задала этот вопрос по ДЗ, но Swagger для уточнения вида и типа данных недоступен, буду ожидать обратной связи уже на основе кода целиком.

2023-02-27 18:04 UTC, painassasin requested changes

2023-02-27 18:04 UTC, painassasin commented on goals/serializers.py
> +        if value < timezone.now():
А если value=None, судя по спеке это поле опциональное.
Такую ошибку и подобные легче отловить, если ставить тайпхинты

2023-02-27 18:04 UTC, painassasin commented on goals/views.py
> +    filterset_class = CommentGoalNameFilter
Данный класс тут не нужен, а вот указать filtersetfields то что нужно, чтобы запросы фильтровались по goal_id
```python
 filterset_fields = ['goal']
 ```

2023-02-28 08:40 UTC, Glassyflute commented on goals/serializers.py
> +        if value < timezone.now():
попробовала с тайпхинтами, но опыта не хватает, все время попадаю на аналоги ошибки - '<' not supported between instances of 'NoneType' and 'datetime.datetime’. В итоге взяла вариант попроще с условием, и проверка даты происходит тогда, когда есть такая дата.

2023-02-28 08:41 UTC, Glassyflute commented on goals/views.py
> +    filterset_class = CommentGoalNameFilter
здесь спасибо!) я пробовала с filterset_fields вначале, но потом не туда посмотрела и не поняла, что оно работало, как надо.

2023-02-28 09:30 UTC, painassasin approved these changes

2023-02-28 09:30 UTC, painassasin commented on goals/serializers.py
> +            return value
Эту строчку табом лучше сдвинуть влево, иначе return из функции неявно выдает None

2023-02-28 09:38 UTC, merged